{% set name = "iscd-advection" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ISCDtoolbox/Advection/archive/refs/tags/v{{ version }}.zip
  sha256: 5c5c6e033faa0b26a413457358577055218b66b4a326aac3b90baf7dbf766062
  patches:
    - CMakeLists.patch

build:
  number: 0
  skip: true  # [py2k or win] # Cannot open include file: 'pthread.h': No such file or directory
  run_exports:
    - {{ pin_subpackage('iscd-advection', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]
    - iscd-commons
  run:
    - iscd-commons

test:
  commands:
    - advect --version || true  # [unix]
    - test -f $PREFIX/lib/libAdvection.so  # [linux]
    - test -f $PREFIX/lib/libAdvection.dylib  # [osx]
    - test -f $PREFIX/include/advect.h
    - test -f $PREFIX/include/ad_calls.h

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'ISCD - Advection'
  description: |
    Advect is a program for solving linear advection problems in two and three dimensions.
  doc_url: https://github.com/ISCDtoolbox/Advection/tree/master/Documentation
  dev_url: https://github.com/ISCDtoolbox/Advection

extra:
  recipe-maintainers:
    - ldallolio
    - fbordeu
